version: '3'
services:
  nginx:
    container_name: wpl_web
    build:
      context: .
      dockerfile: ./docker/config/nginx
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - .:/var/www:cached
    links:
        - php

  php:
    container_name: wpl_php
    build:
      context: .
      dockerfile: ./docker/config/php
    restart: unless-stopped
    volumes:
      - .:/var/www:cached
    environment:
          XDEBUG_CONFIG: "remote_host=${host_lan_ip}"
          PHP_IDE_CONFIG: "serverName=wpl"
    links:
      - mailcatcher

  database:
    container_name: wpl_db
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  mailcatcher:
    container_name: wpl_mailcatcher
    image: instructure/mailcatcher
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "1080:8080"

  phpmyadmin:
    container_name: wpl_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    links:
      - database:db