version: '3'
services:
  nginx:
    container_name: wpl_web
    build:
      context: ./docker/config/
      dockerfile: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www:cached
    links:
        - php

  php:
    container_name: wpl_php
    build:
      context: ./docker/config/
      dockerfile: php
    volumes:
      - .:/var/www:cached
    environment:
          XDEBUG_CONFIG: "remote_host=${host_lan_ip}"
          PHP_IDE_CONFIG: "serverName=wpl"
    links:
      - mailhog

  database:
    container_name: wpl_db
    image: mysql:5.7
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"



  phpmyadmin:
    container_name: wpl_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - database:db


