<?php

declare(strict_types=1);

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * App\ReactLog.
 *
 * @property string                          $log
 * @property bool                            $fixed
 * @property int                             $id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ReactLog whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ReactLog whereFixed($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ReactLog whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ReactLog whereLog($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ReactLog whereUpdatedAt($value)
 * @mixin \Eloquent
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ReactLog newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ReactLog newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ReactLog query()
 */
class ReactLog extends Model
{
    protected $fillable = ['log', 'fixed'];

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('fixed', function (Builder $builder): void {
            $builder->where('fixed', '=', 0);
        });
    }
}
