<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * @property string $log
 * @property bool   $fixed
 * @property int    $id
 */
class ReactLog extends Model
{
    protected $fillable = ['log', 'fixed'];

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('fixed', function (Builder $builder): void {
            $builder->where('fixed', '=', 0);
        });
    }
}
